##### **Simple RNN**

In [1]:
from tensorflow.keras.preprocessing.text import one_hot, Tokenizer

In [2]:
sentence = ["The cat is on the table",
            "The dog is under the table",
            "The cat is under the table",
            "The rainbow is in the sky",
            "The umbrella is important on a rainy day",
            "I love to eat pizza on a rainy day",
            "The cat is on the roof",
            "The wonderful world is full of surprises"]

vocab_size = 10000

In [3]:
sentence

['The cat is on the table',
 'The dog is under the table',
 'The cat is under the table',
 'The rainbow is in the sky',
 'The umbrella is important on a rainy day',
 'I love to eat pizza on a rainy day',
 'The cat is on the roof',
 'The wonderful world is full of surprises']

In [4]:
## One hot representation
onehot_repr = [one_hot(words, vocab_size) for words in sentence]
onehot_repr

[[8797, 486, 3206, 5751, 8797, 4136],
 [8797, 225, 3206, 6779, 8797, 4136],
 [8797, 486, 3206, 6779, 8797, 4136],
 [8797, 8285, 3206, 1305, 8797, 2600],
 [8797, 3513, 3206, 742, 5751, 7007, 6125, 7497],
 [4780, 248, 5022, 2440, 7027, 5751, 7007, 6125, 7497],
 [8797, 486, 3206, 5751, 8797, 6676],
 [8797, 9757, 6011, 3206, 8934, 6575, 1013]]

In [7]:
# Word embedding representation
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8797  486 3206 5751 8797 4136]
 [   0    0    0    0 8797  225 3206 6779 8797 4136]
 [   0    0    0    0 8797  486 3206 6779 8797 4136]
 [   0    0    0    0 8797 8285 3206 1305 8797 2600]
 [   0    0 8797 3513 3206  742 5751 7007 6125 7497]
 [   0 4780  248 5022 2440 7027 5751 7007 6125 7497]
 [   0    0    0    0 8797  486 3206 5751 8797 6676]
 [   0    0    0 8797 9757 6011 3206 8934 6575 1013]]


In [12]:
# Feature representation
dim = 10

# Create the model
model=Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=dim))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step


array([[[-3.57556827e-02, -3.47176790e-02, -2.17077266e-02,
          4.76387031e-02, -4.40451279e-02,  1.33732669e-02,
         -4.90624309e-02,  4.75778840e-02, -4.17218581e-02,
          2.60919370e-02],
        [-3.57556827e-02, -3.47176790e-02, -2.17077266e-02,
          4.76387031e-02, -4.40451279e-02,  1.33732669e-02,
         -4.90624309e-02,  4.75778840e-02, -4.17218581e-02,
          2.60919370e-02],
        [-3.57556827e-02, -3.47176790e-02, -2.17077266e-02,
          4.76387031e-02, -4.40451279e-02,  1.33732669e-02,
         -4.90624309e-02,  4.75778840e-02, -4.17218581e-02,
          2.60919370e-02],
        [-3.57556827e-02, -3.47176790e-02, -2.17077266e-02,
          4.76387031e-02, -4.40451279e-02,  1.33732669e-02,
         -4.90624309e-02,  4.75778840e-02, -4.17218581e-02,
          2.60919370e-02],
        [ 3.55413593e-02,  3.54858525e-02, -3.67913134e-02,
          2.20662467e-02,  3.65345553e-03,  2.94889696e-02,
          2.51127370e-02,  1.67586915e-02,  4.383667

In [15]:
embedded_docs[0]


array([   0,    0,    0,    0, 8797,  486, 3206, 5751, 8797, 4136],
      dtype=int32)

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>