##### **Simple RNN**

In [11]:
from tensorflow.keras.preprocessing.text import one_hot, Tokenizer

In [12]:
sentence = ["The cat is on the table",
            "The dog is under the table",
            "The cat is under the table",
            "The rainbow is in the sky",
            "The umbrella is important on a rainy day",
            "I love to eat pizza on a rainy day",
            "The cat is on the roof",
            "The wonderful world is full of surprises"]

vocab_size = 10000

In [13]:
sentence

['The cat is on the table',
 'The dog is under the table',
 'The cat is under the table',
 'The rainbow is in the sky',
 'The umbrella is important on a rainy day',
 'I love to eat pizza on a rainy day',
 'The cat is on the roof',
 'The wonderful world is full of surprises']

In [14]:
## One hot representation
onehot_repr = [one_hot(words, vocab_size) for words in sentence]
onehot_repr

[[4507, 651, 2193, 938, 4507, 2791],
 [4507, 4521, 2193, 1433, 4507, 2791],
 [4507, 651, 2193, 1433, 4507, 2791],
 [4507, 6320, 2193, 2659, 4507, 2941],
 [4507, 6650, 2193, 6353, 938, 1121, 7812, 6732],
 [8139, 6398, 8514, 477, 211, 938, 1121, 7812, 6732],
 [4507, 651, 2193, 938, 4507, 6659],
 [4507, 9284, 8363, 2193, 9108, 2757, 6695]]

In [15]:
# Tokenizer
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(sentence)
sequences = tokenizer.texts_to_sequences(sentence)

In [16]:
# Word embedding representation
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

# Feature representation
embedding_vector_features=40

[[   0    0    0    0 4507  651 2193  938 4507 2791]
 [   0    0    0    0 4507 4521 2193 1433 4507 2791]
 [   0    0    0    0 4507  651 2193 1433 4507 2791]
 [   0    0    0    0 4507 6320 2193 2659 4507 2941]
 [   0    0 4507 6650 2193 6353  938 1121 7812 6732]
 [   0 8139 6398 8514  477  211  938 1121 7812 6732]
 [   0    0    0    0 4507  651 2193  938 4507 6659]
 [   0    0    0 4507 9284 8363 2193 9108 2757 6695]]


In [20]:
# Create the model
model=Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=embedding_vector_features,input_length=sent_length))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [21]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Train
model.fit(padded_sequences, y, epochs=10, batch_size=2)

NameError: name 'padded_sequences' is not defined